[project]
name = "gpq"
version = "0.1.0"
description = "Add a short description here"
authors = ["liquidcarbon <akscrps@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
